In [1]:
import requests
import pandas as pd
import time
import warnings
warnings.filterwarnings('ignore')

In [2]:
token="–∑–¥–µ—Å—å –¥–æ–ª–∂–µ–Ω –±—ã—Ç—å —Ç–æ–∫–µ–Ω"

In [3]:
group_name="expert_news"
offset=0
count=100
all_posts=[]
all_comments=[]

In [4]:
while offset<1000:
    req=requests.get('https://api.vk.com/method/wall.search',
               params={
                   'access_token': token,
                   'v': 5.131,
                   'domain': group_name,
                   'query': '—Ü–µ–Ω',
                   'count': count,
                   'offset': offset
                   
               })
    res=req.json()['response']['items']
    offset+=100
    all_posts.extend(res)

In [5]:
df = pd.json_normalize(all_posts)
df

,id,from_id,owner_id,date,marked_as_ads,short_text_rate,attachments,is_favorite,post_type,text,...,post_source.platform,post_source.type,reposts.count,reposts.user_reposted,views.count,post_id,parents_stack,zoom_text,carousel_offset,edited
0,261150,-26517977,-26517977,1674467771,0,0.8,"[{'type': 'link', 'link': {'url': 'https://exp...",False,post,–¶–µ–Ω–æ–≤–æ–π –ø–æ—Ç–æ–ª–æ–∫ –Ω–∞ –Ω–µ—Ñ—Ç—å –æ–∫–∞–∑–∞–ª—Å—è –º–∞–ª–æ—ç—Ñ—Ñ–µ–∫—Ç–∏–≤...,...,iphone,api,2,0,336.0,NaN,NaN,NaN,NaN,NaN
1,261148,-26517977,-26517977,1674461038,0,0.8,"[{'type': 'link', 'link': {'url': 'https://exp...",False,post,–í –°–®–ê –Ω–∞–ø–æ–º–Ω–∏–ª–∏ –æ –∫—Ä–∞—Ö–µ —Å–ª–∞–Ω—Ü–µ–≤–∏–∫–æ–≤ –∏ –ø—Ä–∏–∑–≤–∞–ª–∏...,...,NaN,vk,1,0,465.0,NaN,NaN,NaN,NaN,NaN
2,261130,-26517977,-26517977,1674392521,0,0.8,"[{'type': 'link', 'link': {'url': 'https://exp...",False,post,–î–µ—Ñ–∏—Ü–∏—Ç –ª–∏–∫–≤–∏–¥–Ω–æ—Å—Ç–∏ –ø–æ-–ø—Ä–µ–∂–Ω–µ–º—É –∑–∞—Ç—Ä—É–¥–Ω—è–µ—Ç –æ–ø—Ä...,...,NaN,vk,1,0,858.0,NaN,NaN,NaN,NaN,NaN
3,261117,-26517977,-26517977,1674298920,0,0.8,"[{'type': 'link', 'link': {'url': 'https://exp...",False,post,–í –†–æ—Å—Å–∏–∏ –∏–∑-–∑–∞ —Ä–µ–∑–∫–æ–≥–æ —Å–æ–∫—Ä–∞—â–µ–Ω–∏—è –ø–æ—Å—Ç–∞–≤–æ–∫ –∫—Ä–∞...,...,NaN,vk,10,0,2062.0,NaN,NaN,NaN,NaN,NaN
4,261002,154369535,-26517977,1674199454,0,0.8,[],False,reply,–î–µ—Ç–∫–∏ —Ä–µ—à–∏–ª–∏ –∂–∏—Ç—å —Å–∞–º–æ—Å—Ç–æ—è—Ç–µ–ª—å–Ω–æ (üòÜ)...\n–ê –Ω–∞ ...,...,NaN,vk,0,0,NaN,261002.0,[],NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,243415,-26517977,-26517977,1625232000,0,0.8,"[{'type': 'photo', 'photo': {'album_id': -7, '...",False,post,–ù–∞ —Ä–æ—Å—Å–∏–π—Å–∫–æ–º –∞–≤—Ç–æ—Ä—ã–Ω–∫–µ –±–µ—Å–ø—Ä–µ—Ü–µ–¥–µ–Ω—Ç–Ω—ã–π –¥–µ—Ñ–∏—Ü–∏...,...,NaN,vk,1,0,1981.0,NaN,NaN,NaN,NaN,NaN
996,243316,230576110,-26517977,1624646346,0,0.8,[],False,reply,"–Ω–∏—á–µ –ø—É—Å–∫–∞–π –±–∞—Ä—ã–≥–∏ ""–ø—Ä–æ–≤–∞–ª—è—Ç—Å—è"" –∏–º –ø–æ–ª–µ–∑–Ω–æ –±—É–¥...",...,NaN,vk,0,0,NaN,243316.0,[],NaN,NaN,NaN
997,243312,-26517977,-26517977,1624618123,0,0.8,"[{'type': 'photo', 'photo': {'album_id': -7, '...",False,post,–≠–∫—Å–ø–æ—Ä—Ç –≥–∞–∑–∞ –∏–∑ –†–æ—Å—Å–∏–∏ –≤ –∫–æ–Ω—Ç–∏–Ω–µ–Ω—Ç–∞–ª—å–Ω—É—é –ï–≤—Ä–æ–ø...,...,NaN,vk,1,0,1214.0,NaN,NaN,NaN,NaN,NaN
998,243247,-26517977,-26517977,1624444160,0,0.8,"[{'type': 'photo', 'photo': {'album_id': -7, '...",False,post,–í–æ–ª–∞—Ç–∏–ª—å–Ω–æ—Å—Ç—å –Ω–∞–¥–µ–ª–∞–ª–∞ –ø—Ä–æ–±–ª–µ–º. IPO –∫–æ–º–ø–∞–Ω–∏–∏ N...,...,NaN,vk,1,0,657.0,NaN,NaN,NaN,NaN,NaN
999,243173,3341135,-26517977,1624371197,0,0.8,[],False,reply,"–ù–∞—à–∏ –∫—É—Ä–æ—Ä—Ç—ã - —ç—Ç–æ —Ö–∞–º—Å—Ç–≤–æ, –æ—Ç–≤—Ä–∞—Ç–∏—Ç–µ–ª—å–Ω—ã–π —Å–µ—Ä...",...,NaN,vk,0,0,NaN,243173.0,[],True,NaN,NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     1000 non-null   int64
 1   from_id                1000 non-null   int64
 2   owner_id               1000 non-null   int64
 3   date                   1000 non-null   int64
 4   marked_as_ads          1000 non-null   int64
 5   short_text_rate        1000 non-null   float64
 6   attachments            1000 non-null   object
 7   is_favorite            1000 non-null   bool
 8   post_type              1000 non-null   object
 9   text                   1000 non-null   object
 10  hash                   1000 non-null   object
 11  donut.is_donut         1000 non-null   bool
 12  comments.can_post      1000 non-null   int64
 13  comments.count         1000 non-null   int64
 14  likes.can_like         1000 non-null   int64
 15  likes.count            1000 non-null   int64
 16  likes.user_likes       1000 non-null   int64
 17  likes.can_publish      1000 non-null   int64
 18  post_source.platform   649 non-null    object
 19  post_source.type       1000 non-null   object
 20  reposts.count          1000 non-null   int64
 21  reposts.user_reposted  1000 non-null   int64
 22  views.count            737 non-null    float64
 23  post_id                263 non-null    float64
 24  parents_stack          263 non-null    object
 25  zoom_text              75 non-null     object
 26  carousel_offset        19 non-null     float64
 27  edited                 50 non-null     float64
dtypes: bool(2), float64(5), int64(13), object(8)
memory usage: 205.2+ KB

In [7]:
df=df[["id", "owner_id", "date", "text", "comments.count"]]
df.rename(columns={'date': 'post_time','text':'post_text'}, inplace=True)
df=df[df['post_time']>=1630454400]
df=df[df['comments.count']!=0]
df.set_index('id')

,owner_id,post_time,post_text,comments.count
id,,,,
261117,-26517977,1674298920,–í –†–æ—Å—Å–∏–∏ –∏–∑-–∑–∞ —Ä–µ–∑–∫–æ–≥–æ —Å–æ–∫—Ä–∞—â–µ–Ω–∏—è –ø–æ—Å—Ç–∞–≤–æ–∫ –∫—Ä–∞...,1
261089,-26517977,1674148800,"–í –¶–ë –æ–±—ä—è—Å–Ω–∏–ª–∏, –ø–æ—á–µ–º—É –∞—Ä–µ–Ω–¥–æ–≤–∞—Ç—å –∫–≤–∞—Ä—Ç–∏—Ä—É –º–æ–∂...",1
260811,-26517977,1673107800,"–ì–ª–∞–≤–∞ –ú–∏–Ω—ç–Ω–µ—Ä–≥–æ –¢—É—Ä—Ü–∏–∏ –∑–∞—è–≤–∏–ª, —á—Ç–æ –≤ —Å—Ç—Ä–∞–Ω–µ –æ—Ç...",2
260735,-26517977,1672816200,–ü—Ä–æ–≥–Ω–æ–∑—ã –ø–æ –º–∞–∫—Å–∏–º–∞–ª—å–Ω–æ–π —Ü–µ–Ω–µ –∑–æ–ª–æ—Ç–∞ –≤ 2023 –≥–æ...,1
260414,-26517977,1671802200,–¶–µ–Ω—Ç—Ä–∞–ª—å–Ω—ã–π –±–∞–Ω–∫ –†–æ—Å—Å–∏–π—Å–∫–æ–π –§–µ–¥–µ—Ä–∞—Ü–∏–∏ –ø—Ä–æ–¥–ª–∏—Ç ...,1
...,...,...,...,...
244962,-26517977,1630681500,–ü—Ä–∞–≤–∏—Ç–µ–ª—å—Å—Ç–≤–æ —É—Å–∏–ª–∏–≤–∞–µ—Ç –∫–æ–Ω—Ç—Ä–æ–ª—å –∑–∞ —Ä–æ—Å—Ç–æ–º —Ü–µ–Ω...,14
244960,-26517977,1630677900,–†–æ—Å—Å–∏–π—Å–∫–∞—è —Å–µ—Ç—å –º–∞–≥–∞–∑–∏–Ω–æ–≤ –Ω–∏–∑–∫–∏—Ö —Ü–µ–Ω –≤—ã—à–ª–∞ –Ω–∞ ...,2
244919,-26517977,1630606576,–ê–∫—Ü–∏–∏ –¥–Ω—è: –±—É–º–∞–≥–∏ ¬´–†—É—Å–∞–ª–∞¬ª —Ç–æ—Ä–≥–æ–≤–∞–ª–∏—Å—å –ø–æ –ª–µ—Ç–Ω...,1
244879,-26517977,1630494360,–ù–∞ –∫–∞–∫–∏—Ö –ø—Ä–∏–Ω—Ü–∏–ø–∞—Ö –ø–æ—Å—Ç—Ä–æ–∏—Ç—å —Å–±–æ—Ä –∏ —Ö—Ä–∞–Ω–µ–Ω–∏–µ —Ü...,5
244870,-26517977,1630487100,"–û–¥–Ω–∏–º –∏–∑ –∫–ª—é—á–µ–≤—ã—Ö —Ñ–∞–∫—Ç–æ—Ä–æ–≤, —Å–ø–æ—Å–æ–±—Å—Ç–≤—É—é—â–∏—Ö —Ä–æ—Å...",7

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 235 entries, 3 to 863
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              235 non-null    int64
 1   owner_id        235 non-null    int64
 2   post_time       235 non-null    int64
 3   post_text       235 non-null    object
 4   comments.count  235 non-null    int64
dtypes: int64(4), object(1)
memory usage: 11.0+ KB

In [9]:
owner_id=-26517977
posts_id=list(df['id'])

In [11]:
for post_id in posts_id:
    req=requests.get('https://api.vk.com/method/wall.getComments',
               params={
                   'access_token': token,
                   'v': 5.131,
                   'owner_id': owner_id,
                   'post_id': post_id
               })
    time.sleep(1)
    res=req.json()['response']['items']
    all_comments.extend(res)

In [12]:
data = pd.json_normalize(all_comments)
data

,id,from_id,date,text,post_id,owner_id,parents_stack,thread.count,thread.items,thread.can_post,thread.show_reply_button,attachments,deleted
0,261120,710313517,1674315737,–°–µ—Ä—å—ë–∑–Ω–∞—è —Ç–µ–º–∞ –¥–ª—è —Ä–æ—Å—Å–∏–π—Å–∫–æ–≥–æ —Ä—ã–±–æ–≤–æ–¥—Å—Ç–≤–∞,261117.0,-26517977.0,[],0,[],True,True,NaN,NaN
1,261090,254867,1674149226,–∞ –º–æ–∂–µ—Ç –∏ –Ω–µ –±—ã—Ç—å... –ß–µ—Ä–µ–∑ 30 –ª–µ—Ç –∞—Ä–µ–Ω–¥–∞ –±—É–¥–µ—Ç...,261089.0,-26517977.0,[],0,[],True,True,NaN,NaN
2,260812,710313517,1673107987,"–ò–Ω—Ç–µ—Ä–µ—Å–Ω–æ, –æ–Ω–∏ –µ—â—ë –∏ –≤ —Å–≤–æ–µ–π –≤–∞–ª—é—Ç–µ –¥–æ–≥–∞–¥—é—Ç—Å—è ...",260811.0,-26517977.0,[],0,[],True,True,NaN,NaN
3,260813,12697056,1673109630,–ó–∞–ø–∞—Ö –¥–µ–Ω–µ–≥ –º–∞–Ω–∏—Ç –∏ –ø–µ—Ä–µ–≤—ã–±–æ—Ä—ã —Å–∫–æ—Ä–æ.),260811.0,-26517977.0,[],0,[],True,True,NaN,NaN
4,260737,710313517,1672817976,–ö–∞–∫ –º–∏–Ω–∏–º—É–º –Ω–∞—Ü–∏–æ–Ω–∞–ª—å–Ω—ã–µ –±–∏—Ä–∂–∏ –¥–æ–ª–∂–Ω—ã —É–ø—Ä–æ—Å—Ç–∏—Ç...,260735.0,-26517977.0,[],0,[],True,True,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
659,244873,418165222,1630488189,–í–µ–¥—å –ø–æ—á—Ç–∏ –≤–æ –≤—Å–µ—Ö —Ä–µ–≥–∏–æ–Ω–∞—Ö —Ü–µ–Ω—ã –≤ —Å–∞–º–æ–º –¥–µ–ª–µ ...,244870.0,-26517977.0,[],0,[],True,True,NaN,NaN
660,244874,315402790,1630488801,"–°–æ–≥–ª–∞—Å–Ω–æ —Å—Ç–∞—Ç–∏—Å—Ç–∏–∫–µ, –≤ –ê–ª—Ç–∞–µ, –ó–∞–±–∞–π–∫–∞–ª—å–µ, –ö–∞–ª—É...",244870.0,-26517977.0,[],0,[],True,True,NaN,NaN
661,244875,640119947,1630489632,"–†–æ—Å—Ç —Ü–µ–Ω –Ω–∞ –ø—Ä–æ–¥—É–∫—Ç—ã –Ω–µ–∏–∑–±–µ–∂–µ–Ω, –Ω–æ –ü—É—Ç–∏–Ω —Å—Ç–∞—Ä–µ...",244870.0,-26517977.0,[],0,[],True,True,NaN,NaN
662,244888,1693057,1630508529,–ù–∞—Ü–∏–æ–Ω–∞–ª—å–Ω–æ–µ –¥–æ—Å—Ç–æ—è–Ω–∏–µ —É—Ö–æ–¥–∏—Ç –Ω–µ –≤ —Ç–µ —Ä—É–∫–∏,244870.0,-26517977.0,[],0,[],True,True,NaN,NaN
663,244904,219523024,1630566369,–ù–∞–¥–æ –±—ã–ª–æ –ø—Ä–æ—Å—Ç–æ –µ—â—ë –≤ 10–µ –≥–æ–¥–∞ —Å–æ–∑–¥–∞–≤–∞—Ç—å –≥–æ—Å—É...,244870.0,-26517977.0,[],0,[],True,True,NaN,NaN

In [13]:
data=data[["post_id", "text", "date"]]
data.rename(columns={'date': 'comment_time', 'id': 'comment_id'}, inplace=True)
data=data.dropna()

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 661 entries, 0 to 663
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   post_id       661 non-null    float64
 1   text          661 non-null    object
 2   comment_time  661 non-null    int64
dtypes: float64(1), int64(1), object(1)
memory usage: 20.7+ KB

In [15]:
data['post_id'] = data['post_id'].astype(int)
data

     post_id                                               text  comment_time
0     261117         –°–µ—Ä—å—ë–∑–Ω–∞—è —Ç–µ–º–∞ –¥–ª—è —Ä–æ—Å—Å–∏–π—Å–∫–æ–≥–æ —Ä—ã–±–æ–≤–æ–¥—Å—Ç–≤–∞    1674315737
1     261089  –∞ –º–æ–∂–µ—Ç –∏ –Ω–µ –±—ã—Ç—å... –ß–µ—Ä–µ–∑ 30 –ª–µ—Ç –∞—Ä–µ–Ω–¥–∞ –±—É–¥–µ—Ç...    1674149226
2     260811  –ò–Ω—Ç–µ—Ä–µ—Å–Ω–æ, –æ–Ω–∏ –µ—â—ë –∏ –≤ —Å–≤–æ–µ–π –≤–∞–ª—é—Ç–µ –¥–æ–≥–∞–¥—é—Ç—Å—è ...    1673107987
3     260811           –ó–∞–ø–∞—Ö  –¥–µ–Ω–µ–≥ –º–∞–Ω–∏—Ç  –∏ –ø–µ—Ä–µ–≤—ã–±–æ—Ä—ã —Å–∫–æ—Ä–æ.)    1673109630
4     260735  –ö–∞–∫ –º–∏–Ω–∏–º—É–º –Ω–∞—Ü–∏–æ–Ω–∞–ª—å–Ω—ã–µ –±–∏—Ä–∂–∏ –¥–æ–ª–∂–Ω—ã —É–ø—Ä–æ—Å—Ç–∏—Ç...    1672817976
..       ...                                                ...           ...
659   244870  –í–µ–¥—å –ø–æ—á—Ç–∏ –≤–æ –≤—Å–µ—Ö —Ä–µ–≥–∏–æ–Ω–∞—Ö —Ü–µ–Ω—ã –≤ —Å–∞–º–æ–º –¥–µ–ª–µ ...    1630488189
660   244870  –°–æ–≥–ª–∞—Å–Ω–æ —Å—Ç–∞—Ç–∏—Å—Ç–∏–∫–µ, –≤ –ê–ª—Ç–∞–µ, –ó–∞–±–∞–π–∫–∞–ª—å–µ, –ö–∞–ª—É...    1630488801
661   244870  –†–æ—Å—Ç —Ü–µ–Ω –Ω–∞ –ø—Ä–æ–¥—É–∫—Ç—ã –Ω–µ–∏–∑–±–µ–∂–µ–Ω, –Ω–æ –ü—É—Ç–∏–Ω —Å—Ç–∞—Ä–µ...    1630489632
662   244870         –ù–∞—Ü–∏–æ–Ω–∞–ª—å–Ω–æ–µ –¥–æ—Å—Ç–æ—è–Ω–∏–µ —É—Ö–æ–¥–∏—Ç –Ω–µ –≤ —Ç–µ —Ä—É–∫–∏    1630508529
663   244870  –ù–∞–¥–æ –±—ã–ª–æ –ø—Ä–æ—Å—Ç–æ –µ—â—ë –≤ 10–µ –≥–æ–¥–∞ —Å–æ–∑–¥–∞–≤–∞—Ç—å –≥–æ—Å—É...    1630566369

[661 rows x 3 columns]

In [16]:
df.to_csv('expert_posts.csv', index=False)

In [17]:
data.to_csv('expert_comments.csv', index=False)